### ISSUE TITLE
"run -on-widows.bat" opens then closes in less than a second without doing anything

### ISSUE THREAD

**Issue by yaukari** [quantumcore/remote_hacker_probe#13]
https://user-images.githubusercontent.com/75146973/135735711-3c9dfde2-b4c1-41a4-93ac-ea570e00d31e.mp4

**Comment by quantumcore** [comment]
Shift + Right click inside that folder. Select Open Command window here or Open PowerShell window here.

in console, Type the following.
```
> java -jar rhp.jar
```

Tell me here what it says. Most likely, Java is not available in your system environment variables.
